/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * JSONPlaceholder API
 * OpenAPI spec version: 1.0.0
 */
export interface Post {
  userId?: number;
  id?: number;
  title?: string;
  body?: string;
}

export interface Comment {
  postId?: number;
  id?: number;
  name?: string;
  email?: string;
  body?: string;
}

export interface User {
  id?: number;
  name?: string;
  username?: string;
  email?: string;
  phone?: string;
  website?: string;
}
